micronaut:
  application:
    name: financeApi
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1
    sender:
      agent-host: jaeger-svc.ctrl.svc.cluster.local
      agent-port: 6831