apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-api-deploy
  namespace: dev
  labels:
    app: audit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-api
  template:
    metadata:
      labels:
        app: audit-api
    spec:
      containers:
      - name: audit-api
        image: audit-api-openjdk:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
