apiVersion: v1
kind: Service
metadata:
  labels:
    app: finance-api-svc
  name: finance-api-svc
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: finance-api